### ISSUE TITLE
ENH: Incidence rates?

### ISSUE THREAD

**Issue by westurner** [weinbergerlab/excess_pi_covid#14]
Would it be appropriate to review these derived metrics relative to (state, county, metro area,) population count and/or population density?

See also: "ENH: Incidence Rate (per 100,000 persons)" https://github.com/CSSEGISandData/COVID-19/issues/2186#issuecomment-615064077

**Comment by westurner** [comment]
TBH, I'm not sure whether the correct term is "incidence" or "prevalence".

These are not presented relative to state population counts: https://www.washingtonpost.com/graphics/2020/investigations/coronavirus-excess-deaths-may/

**Comment by DanWeinberger** [comment]
A death is a discrete event (you only die once). In the summary table here the final column has deaths per population size (incidence)
