### ISSUE TITLE
BLD: Binder-compatible (repo2docker (REES)) dependency spec for reproducibility

### ISSUE THREAD

**Issue by westurner** [weinbergerlab/excess_pi_covid#15]
It would probably be really easy to binderize this repo for interactive use with BinderHub

Here are a few examples:
- https://mybinder.readthedocs.io/en/latest/sample_repos.html#specifying-an-r-environment-with-a-runtime-txt-file
  - https://github.com/binder-examples/r
- https://github.com/binder-examples/r-conda

**Comment by DanWeinberger** [comment]
Thanks. the washpost has started maintaining a GitHub repo with this code that is a bit more user friendly and we'll organized than ours. Might be better to apply it to that

**Comment by westurner** [comment]
Do you have the link to that repo?
It may have been in the NewsArticle

**Comment by westurner** [comment]
FWIW: "Show HN: LaTeX.css – Make your website look like a LaTeX document" https://news.ycombinator.com/item?id=23282207

https://github.com/neilpanchal/spinzero-jupyter-theme

**Comment by DanWeinberger** [comment]
https://github.com/wpinvestigative/excess_deaths_covid19
------------------
Associate Professor
Epidemiology of Microbial Diseases
Yale School of Public Health

**Comment by westurner** [comment]
Notably, they have failed to present incidence rates (per 100,000 people) which are indeed in the table presented in the ScholarlyArticle. I suppose I'll raise that issue with WaPo.
https://github.com/weinbergerlab/excess_pi_covid/issues/14

Do you think they should link to/ cite their GitHub repo?

**Comment by DanWeinberger** [comment]
Their repo is cited in the technical box in the article. I'm not sure the
refer to it as incidence but will check

Dan
