### ISSUE TITLE
weekly state-level P&I excess?

### ISSUE THREAD

**Issue by nickblink** [weinbergerlab/excess_pi_covid#6]
First, I really like the paper. 
I am trying to use weekly, state-level P&I excess deaths in my own project. Is that available here? There are weekly national excess P&I deaths in table S1 and aggregate state excess P&I deaths in table 1 so I would want a fusion of both. I had the issue before where only national estimates of expected P&I are provided by the CDC so I couldn't do this, but since yall use your own model this should fix that issue.
Of course, I could just figure out the code and tweak it to give me these results, but I'd rather not do that if I don't have to...

**Comment by DanWeinberger** [comment]
all of the data we use are pulled from cdcfluview package. You can get state or national for P&I deaths, ILI, and NREVSS data
